/* CREATE TABLE AND INSERT DATA WITH EXCHANGE RATES FOR DIFERENT CURRENCIES */

CREATE SCHEMA EXCHANGE;

CREATE or REPLACE TABLE RAW.EXCHANGE.EXCHANGE_RATES (
    NATION_ID NUMBER(38,0),
    CURRENCY_FROM VARCHAR(10),
    CURRENCY_TO VARCHAR(10),
    RATE FLOAT
);

-- Algeria (Dinar)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (0, 'USD', 'DZD', 134.72);

-- Argentina (Peso)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (1, 'USD', 'ARS', 102.50);

-- Brazil (Real)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (2, 'USD', 'BRL', 5.30);

-- Canada (Dollar)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (3, 'USD', 'CAD', 1.23);

-- Egypt (Pound)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (4, 'USD', 'EGP', 16.80);

-- Ethiopia (Birr)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (5, 'USD', 'ETB', 45.00);

-- France (Euro)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (6, 'USD', 'EUR', 0.90);

-- Germany (Euro)
INSERT INTO CURRENCY.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (7, 'USD', 'EUR', 0.90);

-- India (Rupee)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (8, 'USD', 'INR', 74.50);

-- Indonesia (Rupiah)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (9, 'USD', 'IDR', 14000.00);

-- Iran (Rial)
INSERT INTO CURRENCY.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (10, 'USD', 'IRR', 42000.00);

-- Iraq (Dinar)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (11, 'USD', 'IQD', 1450.00);

-- Japan (Yen)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (12, 'USD', 'JPY', 110.50);

-- Jordan (Dinar)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (13, 'USD', 'JOD', 0.71);

-- Kenya (Shilling)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (14, 'USD', 'KES', 110.00);

-- Morocco (Dirham)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (15, 'USD', 'MAD', 9.50);

-- Mozambique (Metical)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (16, 'USD', 'MZN', 63.00);

-- Peru (Sol)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (17, 'USD', 'PEN', 4.00);

-- China (Yuan)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (18, 'USD', 'CNY', 6.50);

-- Romania (Leu)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (19, 'USD', 'RON', 4.10);

-- Saudi Arabia (Riyal)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (20, 'USD', 'SAR', 3.75);

-- Vietnam (Dong)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (21, 'USD', 'VND', 23000.00);

-- Russia (Ruble)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (22, 'USD', 'RUB', 80.00);

-- United Kingdom (Pound)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (23, 'USD', 'GBP', 0.70);

-- United States (Dollar, should technically be 1 USD to USD, but for completeness)
INSERT INTO RAW.EXCHANGE.EXCHANGE_RATES (NATION_ID, CURRENCY_FROM, CURRENCY_TO, RATE)
VALUES (24, 'USD', 'USD', 1.00);