CREATE ROLE SALES_CUSTOMER;

GRANT USAGE ON DATABASE ANALYTICS TO ROLE SALES_CUSTOMER;

GRANT USAGE ON SCHEMA ANALYTICS.DELIVERY_ANALYTICS TO ROLE SALES_CUSTOMER;

GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS.DELIVERY_ANALYTICS TO ROLE SALES_CUSTOMER;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS.DELIVERY_ANALYTICS TO ROLE SALES_CUSTOMER;
